# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixSfqcocca7JwLShWBFNnt1hF0P9nktD
"""

import numpy as np

vec = np.random.randint(1, 11, size=100) #создаём
a = np.mean(vec > 7) * 100 #считаем

print(f"Процент: {a:.2f}")