# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQIx5WfyQHTxZgUq7ErVBKIolBiHfWqx
"""

a = input().split()

b = a[::-1]

print(b)