# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_yLh_R8XwegTKz4mcCNf0O9wK0JdYfR
"""

i = list(input())
print(''.join(i[::2]))