# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUXIV3BYMUSdG1Guyban_Ii9pMQbphxr
"""

text = input()
symbol = input()

doubled_text = text.replace(symbol, symbol * 2)

print(doubled_text)