# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZk3D7rqdMye3QplG0cYVVZyl8xctPWP
"""

input_string = input()

count_x = input_string.count('x')
count_y = input_string.count('y')

print(count_x, count_y)