# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f1aCk2pGz01Trm6wqz6G7oay2q2sNDiF
"""

i = float(input('Введите число: '))
q = int(input('Какое количество знаков после запятой оставить? '))

print(round(i,q))