# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCHIQqLjW34jvRqCB5D2X6TGpDM2mc4Y
"""

f = int(input('Введите первое число: '))
s = int(input('Введите второе число: '))

out = int((f + s) / 2)
print(out)