# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EhsuDmXSfNNRjPguRLOLPLrrACUCvmf
"""

i = list(input())
q = [int(item) for item in i]
print(sum(q))