# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_tWp2AV44sd6jLZoLxAVXeG7A11d5Qx
"""

a = int(input())
o = 1

for i in range(1, a+1):
  o *= i

print(o)