# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eGBWE9-dFoxhtlMBezS3C1xU8GP6rOSf
"""

a = int(input())

for i in range(1, a+1):
  if i % 7 == 0:
    print(i)