# -*- coding: utf-8 -*-
"""2_5_1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0n4tSfqGBMgXhfqUoDlulwNxJZdKjJM
"""

import pandas as pd

customers = pd.read_csv('Customers.csv', sep=';')

customers = customers.dropna()

customers

customers_group = customers.groupby('Profession')['Income'].mean()