# -*- coding: utf-8 -*-
"""2_3_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txcQM4KHLCVsotyy4Rw9bY2vsXUSlLut
"""

import pandas as pd

df = pd.DataFrame({
    'Name': ['Alexa', 'Alice', 'Nik', 'Violeta', 'Felix', 'Adrian', 'Marinette'],
    'Age': [18, 18, 19, 14, 16, 16, 15],
    'Sex': ['fermale', 'fermale', 'male', 'fermale', 'male', 'male', 'fermale'],
    'Sity': ['Bratsk', 'Moscow', 'Omsk', 'Moscow', 'London', 'Paris', 'Paris']
})

print(df.head(3))
print(df.head(-3))

df.to_csv('Teenagers')