# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18oRyf4FssK_BtXH1z25qwmcRhtB-Po6T
"""

def f_max(l):

    #когда пусто
    if not l:
        return None

    #если что-то есть
    if len(l) == 1:
        return l[0]

    max_r = f_max(l[1:])

    if max_r is None or l[0] > max_r:
        return l[0]
    else:
        return max_r

my_list = [3, 7, 1, 9, 4, 6, 8, 2]
result = f_max(my_list)
print("Максимальное число:", result)

