# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ocZF95WrjNAULmLo_Etpy74XnjaubDU
"""

i = int(input())

if i % 2 == 0:
  print ('Данное число четное')
else:
  print ('Данное число четное')