# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ocZF95WrjNAULmLo_Etpy74XnjaubDU
"""

i = int(input())
i2 = int(input())

if i > i2:
  print (i)
else:
  print(i2)