# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ocZF95WrjNAULmLo_Etpy74XnjaubDU
"""

x = int(input())
y = int(input())

if x % 2 == 0:
  if y % 2 == 0:
    print('NO')
  else:
    print ('YES')
else:
  if y % 2 == 0:
    print('YES')
  else:
    print('NO')